
spring:
   datasource:
         url: jdbc:mysql://localhost:3306/sample
         username: root
         password: Subho***94
         driver-class-name: com.mysql.jdbc.Driver
   jpa:
     hibernate:
          naming:
             physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
